source 'https://rubygems.org'

gem 'rails', '~> 5.1.5'

gem 'bootstrap', '~> 4.1.0'
gem 'config'
gem 'coffee-rails'
gem 'decent_decoration'
gem 'decent_exposure'
gem 'faker'
gem 'gretel'
gem 'jquery-rails'
gem 'kaminari'
gem 'pg', '0.21.0'
gem 'puma'
gem 'pry-rails'
gem 'slim'
gem 'simple_form'
gem 'spring'
gem 'turbolinks'

ruby '2.5.0'
