defaults: &defaults
  adapter:  postgresql
  host:     localhost
  encoding: utf8
  pool:     10
  username: mike
  password: password
  template: template0

development:
  <<: *defaults
  database: quotation_dev
