# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211a8b54cea4840845cb150f516dc96a7aa0a6d566604b0e7d1d0fa6e372818f68d1ed2552d541a287289cc0815c31d3530df825e71758d98bd880e3a8f0a836

test:
  secret_key_base: e00cc215e70dfff0b1118d3070f41598d858eed64063c726450cefdc48be9ea0b96dcfdfd31dea62f5c659a9eb6c258998ec3864dbdcb15a20c1e1d852e815d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
